### ISSUE TITLE
Can't get it work on Al Minhad AFB in the GULF

### ISSUE THREAD

**Issue by VJS17-Fire** [rkusa/DATIS#86]
Hi,

I tested the script on the Caucasus map at Batumi. It worked fine.

Then I tried it in a mission at Al Minhad AFB on the Persian Gulf map. I tried it with Al Minhad AFB and with OMDM (the name of the base via AI radio). Nothing works.

Any ideas?

**Comment by HILOK** [comment]
hi @rkusa, thanks for this awesome addition to DCS !!

i am also having problems getting it work though, and thought i'd chime in here. did a lot of testing, and ended up here, where i found your test mission. only thing i changed was adding a client a/c in order to tune in and listen to ATIS. 
unfortunately i could'nt get it to work either. any help highly appreciated : )
thanks

[DATIS.log](https://github.com/rkusa/DATIS/files/6183065/DATIS.log)
[DATIS Al Minhad AFB.zip](https://github.com/rkusa/DATIS/files/6183098/DATIS.Al.Minhad.AFB.zip)
![DATIS-2](https://user-images.githubusercontent.com/76898536/112009183-74d3fc80-8b26-11eb-815b-a1d3c20d226e.JPG)
![DATIS-1](https://user-images.githubusercontent.com/76898536/112009212-7ac9dd80-8b26-11eb-88a3-33fcd90fd323.JPG)

**Comment by rkusa** [comment]
@HILOK Thanks for the report and already including the logs and mission file. The attached mission works fine for me and the logs look good, so I am unable to spot an issue in your setup I am afraid. Does it work for you for other airfields, or is it the same for all of them?

**Comment by HILOK** [comment]
thanks for the quick reply! i did lots of trial & error this afternoon. caucasus, nevada, gulf. static object, situation. f16/f18/f5. it didn't work for me. windows TTS is installed & working. could it be win firewall blocking execution of the TTS commands? -did not get any alarms though...

**Comment by rkusa** [comment]
The firewall will not block the execution of the TTS command if you are using the Windows TTS. I suppose you've double checked that you are on the same frequency as the ATIS station? Because there is something that seem wrong on your client list. Once I have a client on the same frequency as the ATIS station, the SRS client list shows the frequency of that client:

![image](https://user-images.githubusercontent.com/409021/112063412-a9b17500-8b61-11eb-9d6f-d110f9230230.png)

Once I leave the frequency, it only shows `---` instead of the frequency.

**Comment by HILOK** [comment]
interesting point. as can be seen on the cockpit screeny on the bottom left, SRS indicates the correct frq. here's a zoom of it:
![DATIS-3](https://user-images.githubusercontent.com/76898536/112111552-a09dc380-8bb4-11eb-885c-0e19068ccc57.JPG)

but we might be onto sth here...

**Comment by HILOK** [comment]
my srs server settings:
![srs-1](https://user-images.githubusercontent.com/76898536/112115015-00966900-8bb9-11eb-83cc-a409a6710e9f.JPG)

**Comment by HILOK** [comment]
could some SRS settings be the cause? -didn't change much to the default settings though...
any help highly appreciated : )

**Comment by rkusa** [comment]
@HILOK I don't think so, but you could still try to toggle Coalition Security, Line of Sight and Distance Limitations off for the sake of testing it. I have Line of Sight and Distance Limitations on all the time, and the F18 is close and in line of sight in your example mission, so I don't expect this to be the issue. All stations are BLUE by default, so Coalition Security could prevent the stations from working for RED units, but as far as I remember, the F18 was also BLUE in your example mission. Anyway, you could still try toggling those options to see if it makes a difference.

**Comment by HILOK** [comment]
thanks, but as you are saying, those factors shouldn't come into play. other than that, can you think of any reason it wouldn't work for me? -i mean, everything else i have running around dcs, srs, vaicom pro, moose, and other scripts, all work like a charm.

**Comment by HILOK** [comment]
ok great! - got it to work : )

now believe it or not, for some reason beyond my imagination, the SECURE COALITION RADIOS option within SRS server did the trick. had to tick it OFF.
anyway double-checked again, and my a/c as well as the airfield are on the same coalition (blue). it also worked for you, so...

thanks a lot for your help, not to forget this awesome ATIS addition!!
cheers

**Comment by HILOK** [comment]
2021-03-25 13:35:26.2680 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Test Frequency: 247200000 
2021-03-25 13:35:26.2680 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Test Frequency: 120300000 
2021-03-25 13:35:26.2680 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Global Frequency: 248220000 
2021-03-25 13:35:26.3330 | Ciribob.DCS.SimpleRadio.Standalone.Server.UI.MainWindow.MainViewModel | DCS-SRS Server Running - 1.9.5.0 
2021-03-25 13:35:27.3830 | Ciribob.DCS.SimpleRadio.Standalone.Common.UpdaterChecker | Running latest stable version: 1.9.5.0 
2021-03-25 13:35:31.3241 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.NatHandler | Failed to open port with UPNP/NAT Open.Nat.NatDeviceNotFoundException: Exception of type 'Open.Nat.NatDeviceNotFoundException' was thrown.
   at Open.Nat.NatDiscoverer.<DiscoverDeviceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ciribob.DCS.SimpleRadio.Standalone.Server.Network.NatHandler.<OpenNAT>d__8.MoveNext()
2021-03-25 13:35:34.1998 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Error receving audio UDP for client A blocking operation was interrupted by a call to WSACancelBlockingCall System.Net.Sockets.SocketException (0x80004005): A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at System.Net.Sockets.UdpClient.Receive(IPEndPoint& remoteEP)
   at Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter.Listen()
2021-03-25 13:35:34.1998 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Error processing Sending Queue UDP Packet: The operation was canceled. 
2021-03-25 13:35:34.1998 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Failed to Process UDP Packet: The operation was canceled. 
2021-03-25 13:35:41.1278 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerState | Unable to read banned.txt System.IO.FileNotFoundException: Could not find file 'C:\Program Files\DCS-SimpleRadio-Standalone\banned.txt'.
File name: 'C:\Program Files\DCS-SimpleRadio-Standalone\banned.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerState.PopulateBanList()
2021-03-25 13:35:41.1368 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Test Frequency: 247200000 
2021-03-25 13:35:41.1368 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Test Frequency: 120300000 
2021-03-25 13:35:41.1368 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Global Frequency: 248220000 
2021-03-25 13:35:41.1978 | Ciribob.DCS.SimpleRadio.Standalone.Server.UI.MainWindow.MainViewModel | DCS-SRS Server Running - 1.9.5.0 
2021-03-25 13:35:41.7820 | Ciribob.DCS.SimpleRadio.Standalone.Common.UpdaterChecker | Running latest stable version: 1.9.5.0 
2021-03-25 13:35:45.1539 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Error receving audio UDP for client A blocking operation was interrupted by a call to WSACancelBlockingCall System.Net.Sockets.SocketException (0x80004005): A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at System.Net.Sockets.UdpClient.Receive(IPEndPoint& remoteEP)
   at Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter.Listen()
2021-03-25 13:35:45.1539 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Failed to Process UDP Packet: The operation was canceled. 
2021-03-25 13:35:45.1539 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Error processing Sending Queue UDP Packet: The operation was canceled. 
2021-03-25 13:35:56.3044 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerState | Unable to read banned.txt System.IO.FileNotFoundException: Could not find file 'C:\Program Files\DCS-SimpleRadio-Standalone\banned.txt'.
File name: 'C:\Program Files\DCS-SimpleRadio-Standalone\banned.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerState.PopulateBanList()
2021-03-25 13:35:56.3134 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Test Frequency: 247200000 
2021-03-25 13:35:56.3134 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Test Frequency: 120300000 
2021-03-25 13:35:56.3134 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Global Frequency: 248220000 
2021-03-25 13:35:56.3744 | Ciribob.DCS.SimpleRadio.Standalone.Server.UI.MainWindow.MainViewModel | DCS-SRS Server Running - 1.9.5.0 
2021-03-25 13:35:56.9154 | Ciribob.DCS.SimpleRadio.Standalone.Common.UpdaterChecker | Running latest stable version: 1.9.5.0 
2021-03-25 13:35:59.8173 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Error receving audio UDP for client A blocking operation was interrupted by a call to WSACancelBlockingCall System.Net.Sockets.SocketException (0x80004005): A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at System.Net.Sockets.UdpClient.Receive(IPEndPoint& remoteEP)
   at Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter.Listen()
2021-03-25 13:35:59.8173 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Failed to Process UDP Packet: The operation was canceled. 
2021-03-25 13:35:59.8173 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Error processing Sending Queue UDP Packet: The operation was canceled. 
2021-03-25 13:37:38.2467 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerState | Unable to read banned.txt System.IO.FileNotFoundException: Could not find file 'C:\Program Files\DCS-SimpleRadio-Standalone\banned.txt'.
File name: 'C:\Program Files\DCS-SimpleRadio-Standalone\banned.txt'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerState.PopulateBanList()
2021-03-25 13:37:38.2467 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Test Frequency: 247200000 
2021-03-25 13:37:38.2467 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Test Frequency: 120300000 
2021-03-25 13:37:38.2467 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Adding Global Frequency: 248220000 
2021-03-25 13:37:38.3167 | Ciribob.DCS.SimpleRadio.Standalone.Server.UI.MainWindow.MainViewModel | DCS-SRS Server Running - 1.9.5.0 
2021-03-25 13:37:38.8661 | Ciribob.DCS.SimpleRadio.Standalone.Common.UpdaterChecker | Running latest stable version: 1.9.5.0 
2021-03-25 13:37:43.3076 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.NatHandler | Failed to open port with UPNP/NAT Open.Nat.NatDeviceNotFoundException: Exception of type 'Open.Nat.NatDeviceNotFoundException' was thrown.
   at Open.Nat.NatDiscoverer.<DiscoverDeviceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ciribob.DCS.SimpleRadio.Standalone.Server.Network.NatHandler.<OpenNAT>d__8.MoveNext()
2021-03-25 13:40:54.6897 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2021-03-25 13:40:54.6897 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Removed Disconnected Client GJZT3BHIS_2PSfr5Ep9DhQ 
2021-03-25 13:42:10.3849 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2021-03-25 13:42:10.3849 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Removed Disconnected Client ZP_KIrWSTpG2tH9dqsv1BQ 
2021-03-25 13:43:31.4048 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2021-03-25 13:43:31.4048 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2021-03-25 13:43:31.4048 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Removed Disconnected Client E1faq0A6RNqUkk8QPaNJBw 
2021-03-25 13:48:23.3029 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2021-03-25 13:48:23.3029 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Removed Disconnected Client 56GibpVjT02H9YiQIocNpA 
2021-03-25 13:50:26.7003 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2021-03-25 13:50:26.7003 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Removed Disconnected Client HoJdcTKqRgSENV6TggqdVg 
2021-03-25 13:52:19.0295 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2021-03-25 13:52:19.0295 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Removed Disconnected Client lvrSrk4KSMeYXSum4G4ZAw 
2021-03-25 13:55:06.5081 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2021-03-25 13:55:06.5081 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Removed Disconnected Client yABQ_eWtSjW7cM_1n91Giw 
2021-03-25 13:55:20.5406 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2021-03-25 13:55:20.5406 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Removed Disconnected Client IczKwxOhQ0CVMBO4ROE8bw 
2021-03-25 13:59:15.9496 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2021-03-25 13:59:15.9496 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Removed Disconnected Client NAxSSyxKRSKG9_-K3QQcYA 
2021-03-25 14:07:12.0725 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Disconnecting Client 
2021-03-25 14:07:12.0725 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.ServerSync | Removed Disconnected Client Li2H9D-rzk6v7mAJLtLTKA 
2021-03-25 14:07:13.3417 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Error receving audio UDP for client A blocking operation was interrupted by a call to WSACancelBlockingCall System.Net.Sockets.SocketException (0x80004005): A blocking operation was interrupted by a call to WSACancelBlockingCall
   at System.Net.Sockets.Socket.ReceiveFrom(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint& remoteEP)
   at System.Net.Sockets.UdpClient.Receive(IPEndPoint& remoteEP)
   at Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter.Listen()
2021-03-25 14:07:13.3417 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Error processing Sending Queue UDP Packet: The operation was canceled. 
2021-03-25 14:07:13.3417 | Ciribob.DCS.SimpleRadio.Standalone.Server.Network.UDPVoiceRouter | Failed to Process UDP Packet: The operation was canceled.

**Comment by rkusa** [comment]
I am glad you found the issue! I actually had `SECURE COALITION RADIOS` off during my testing and was just guessing that this shouldn't be an issue. But good to know that there is one. I'll look into it eventually (or add a note about this restriction to the README) 👍
